{
    'name': "Emata HMS",

    'summary': 'Emata HMS',

    'description': '',

    'author': "Emata",
    'website': "https://emata.com.tr",
    'category': 'Tools',
    'version': '17.0.0.0',
    'application': True,
    'sequence': 1,
    'installable': True,

    'depends': [
        'base',
        'mail',
        'product',
        'project',
        'hr',
        'web_responsive',
        'disable_odoo_online',
        'sale',
        'point_of_sale',
    ],

    'data': [
        'security/global_security_rules.xml',
        'security/ir.model.access.csv',

        'views/project_view.xml',
        'views/medication_request_view.xml',
        'views/analysis_request_view.xml',
        'views/image_request_view.xml',
        'views/general_clinic_visit_view.xml',
        'views/clinic_view.xml',
        'views/icd10_view.xml',
        'views/mh_referral_view.xml',
        'views/mh_gap_view.xml',
        'views/mh_awareness_view.xml',
        'views/mh_pmplus_view.xml',
        'views/rhs_anc_view.xml',
        'views/rhs_anc_visit_view.xml',
        'views/rhs_pnc_view.xml',
        'views/rhs_pnc_visit_view.xml',
        'views/rhs_delivery_view.xml',
        'views/rhs_edc_view.xml',
        'views/rhs_infertility_treatment_view.xml',
        'views/rh_awareness.xml',
        'views/rhs_fp_view.xml',
        'views/rhs_hospitalization_view.xml',
        'views/rhs_hospitalization_monitoring_view.xml',
        'views/rhs_surgery_view.xml',
        'views/vital_signs_view.xml',
        'views/labor_monitoring_view.xml',
        'views/post_surgery_view.xml',
        'views/master_models_view.xml',
        'views/res_partner_view.xml',
        'views/product_template_view.xml',
        'views/dial_nephrology_view.xml',
        'views/dial_urology_view.xml',
        'views/dial_lithotripsy_view.xml',
        'views/dial_prescription_view.xml',
        'views/dial_kidney_history_view.xml',
        'views/dial_visit_view.xml',
        'views/nutrition_group_session.xml',
        'views/nutrition_screening_child.xml',
        'views/nutrition_screening_woman.xml',
        'views/nutrition_stabilization_center.xml',
        'views/chw_group_session.xml',
        'views/chw_individual_session.xml',
        'views/rhs_gynochological_clinic_visit_view.xml',
        'views/patient_admission_view.xml',
        'views/patient_admission_surgery_view.xml',
        'views/patient_admission_visit_view.xml',
        'views/daily_necessity_view.xml',
        'views/daily_observation_view.xml',
        'views/necessity_giving_view.xml',
        'views/surgical_procedure_view.xml',
        'views/histories_view.xml',
        'views/pediatric_incubator_admission_view.xml',
        'views/pediatric_ward_admission_view.xml',
        'views/pediatric_surgery_view.xml',
        'views/pediatric_clinic_view.xml',
        'views/pediatric_surgery_clinic_view.xml',
        'views/pediatric_phototherapy_view.xml',
        'views/pediatric_icu_view.xml',
        'views/pediatric_nicu_view.xml',
        'views/pediatric_newborn_examination_view.xml',
        'views/referral_view.xml',

        'data/sequence_data.xml',
        'data/hms_service_data.xml',

        'views/menus_view.xml',
    ],
}
